### ISSUE TITLE
URL does not change when swiching from one page to another

### ISSUE THREAD

**Issue by taikis** [giacomoferretti/forks-diff#2]
Hi. Thank you for this useful extension.  
The GitHub URL does not change when I move from one page to another when this extension enabled.  

### screenshot

https://user-images.githubusercontent.com/60678028/187073681-9bd0ddfc-4681-40c8-8cbd-47163897f7dd.mov

### Steps to reproduce

1. Enable this extension.
1. visit any repository.
1. click something. ex) "Issue"

### Expected behaviour
- The Url should end with "/issue".
- The Issue tab should be underlined.

### Environment
macOS 12.5.1  
Chrome 104.0.5112.101（Official Build） （x86_64）  
Forks Diff Counter for GitHub v1.2.1

**Comment by taikis** [comment]
I tried this steps in FireFox. I was able to reproduce the same problem with Firefox.  
In addition, the "Load Diff" button does not display in Firefox.    
I don't know what is causing this problem.

**Comment by giacomoferretti** [comment]
Oh, this is a BIG problem... I'm so sorry, I thought it was [GitHub's problem](https://github.com/giacomoferretti/forks-diff/issues/1#issuecomment-1207784446).

Thanks for the report and the detailed description, I'm gonna look into it soon. In the meantime, please disable the extension so that you can use GitHub normally.

**Comment by taikis** [comment]
Thank you for your reply. I will look for a solution to this issue too.  
Were you able to reproduce this bug?
